### ISSUE TITLE
Python histograms fails somethimes

### ISSUE THREAD

**Issue by ludovicc** [LREN-CHUV/algorithm-repository#3]
Seen on CLM Vertex, with research + CLM datasets:

                "PARAM_variables=rs610932_a",
                "CHRONOS_JOB_NAME=python_histograms_bab479f1_1b1b_4e03_b381_dfa4f6893111",
                "PARAM_grouping=dataset,gender,agegroup,alzheimerbroadcategory",
                "OUT_JDBC_JAR_PATH=/usr/lib/R/libraries/postgresql-9.4-1201.jdbc41.jar",
                "OUT_JDBC_PASSWORD=aDB/neuroinfo",
                "PARAM_covariables=",
                "mesos_task_id=ct:1507726483217:2:python_histograms_bab479f1_1b1b_4e03_b381_dfa4f6893111:",
                "CHRONOS_RESOURCE_DISK=256.0",
                "DOCKER_IMAGE=hbpmip/python-histograms:4cb93ea",
                "MESOS_SANDBOX=/mnt/mesos/sandbox",
                "OUT_JDBC_DRIVER=org.postgresql.Driver",
                "PARAM_query=select rs610932_a,dataset,gender,agegroup,alzheimerbroadcategory from mip_local_features where rs610932_a is not null and dataset is not null and gender is not null and agegroup is not null and alzheimerbroadcategory is not null ",
                "CHRONOS_RESOURCE_CPU=0.5",
                "IN_JDBC_URL=jdbc:postgresql://hos49130.intranet.chuv:31433/research",
                "OUT_JDBC_URL=jdbc:postgresql://hos49130.intranet.chuv:31433/woken",
                "IN_JDBC_USER=research",
                "NODE=hos49130.intranet.chuv",
                "JOB_ID=bab479f1-1b1b-4e03-b381-dfa4f6893111",
                "OUT_JDBC_USER=woken",
                "PARAM_meta={\"agegroup\":{\"enumerations\":[{\"code\":\"-50y\",\"label\":\"-50y\"},{\"code\":\"50-59y\",\"label\":\"50-59y\"},{\"code\":\"60-69y\",\"label\":\"60-69y\"},{\"code\":\"70-79y\",\"label\":\"70-79y\"},{\"code\":\"+80y\",\"label\":\"+80y\"}],\"description\":\"Age Group\",\"methodology\":\"mip-cde\",\"label\":\"Age Group\",\"code\":\"agegroup\",\"type\":\"polynominal\"},\"alzheimerbroadcategory\":{\"enumerations\":[{\"code\":\"AD\",\"label\":\"Alzheimer's disease\"},{\"code\":\"CN\",\"label\":\"Cognitively Normal\"},{\"code\":\"Other\",\"label\":\"Other\"}],\"description\":\"There will be two broad categories taken into account. Alzheimer's disease (AD) in which the diagnostic is 100% certain and \\\"Other\\\" comprising the rest of Alzheimer's related categories. The \\\"Other\\\" category refers to Alzheime's related diagnosis which origin can be traced to other pathology eg. vascular. In this category MCI diagnosis can also be found. In summary, all Alzheimer's related diagnosis that are not pure.\",\"methodology\":\"mip-cde\",\"label\":\"Alzheimer Broad Category\",\"code\":\"alzheimerbroadcategory\",\"type\":\"polynominal\"},\"dataset\":{\"enumerations\":[{\"code\":\"edsd\",\"label\":\"EDSD\"},{\"code\":\"adni\",\"label\":\"ADNI\"},{\"code\":\"ppmi\",\"label\":\"PPMI\"}],\"description\":\"Variable used to differentiate datasets.\",\"label\":\"Dataset\",\"code\":\"dataset\",\"type\":\"polynominal\"},\"rs610932_a\":{\"sql_type\":\"int\",\"enumerations\":[{\"code\":0,\"label\":0},{\"code\":1,\"label\":1},{\"code\":2,\"label\":2}],\"description\":\"\",\"methodology\":\"lren-nmm-volumes\",\"label\":\"rs610932_A\",\"code\":\"rs610932_a\",\"type\":\"polynominal\"},\"gender\":{\"enumerations\":[{\"code\":\"M\",\"label\":\"Male\"},{\"code\":\"F\",\"label\":\"Female\"}],\"description\":\"Gender of the patient - Sex assigned at birth\",\"methodology\":\"mip-cde\",\"label\":\"Gender\",\"code\":\"gender\",\"length\":1,\"type\":\"binominal\"}}",
                "HOST=hos49130.intranet.chuv",
                "IN_JDBC_JAR_PATH=/usr/lib/R/libraries/postgresql-9.4-1201.jdbc41.jar",
                "CHRONOS_RESOURCE_MEM=512.0",
                "MESOS_CONTAINER_NAME=mesos-3987976c-26a3-415d-8263-f8db921fb1b4",
                "IN_JDBC_PASSWORD=r5s3a6c9d8p2v",
                "CHRONOS_JOB_OWNER=admin@mip.chuv.ch",
                "IN_JDBC_DRIVER=org.postgresql.Driver",
                "PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "LC_ALL=C.UTF-8",
                "COMPUTE_IN=/data/in",
                "COMPUTE_OUT=/data/out",
                "MODEL=histograms",
                "FUNCTION=python-histograms",
                "CODE=histo",
                "NAME=Histograms"

**Comment by mirco-nasuti** [comment]
Should be fixed ! Still have to test it on the CLM Vertex.

**Comment by ludovicc** [comment]
Fixed
